---
builds:
  - main: ./cmd/myapp/main.go
    ldflags:
      - '-s -w -X github.com/hoto/myapp/pkg/config.Version={{.Version}} -X github.com/hoto/myapp/pkg/config.ShortCommit={{.ShortCommit}} -X github.com/hoto/myapp/pkg/config.BuildDate={{.Date}}'
    env:
      - CGO_ENABLED=0
archive:
  format: binary
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - '^Docs:'
      - '^Test:'
      - '^Update readme'
      - '^Update readme.*'
