---
version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.11.3
    working_directory: /go/src/github.com/hoto/myapp
    steps:
      - checkout
      - run: make dependencies
      - run: make test
  github-release:
    docker:
      - image: circleci/golang:1.11.3
    working_directory: /go/src/github.com/hoto/myapp
    steps:
      - checkout
      - run: make github-release

workflows:
  version: 2
  untagged-workflow:
    jobs:
      - test
  tagged-workflow:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
      - github-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.*)*/
